AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stream Simulation Lambda function for DynamoDB access

Resources:
  StreamSimulationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stream-simulation-function
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 256
      Timeout: 30
      Policies:
        - DynamoDBReadPolicy:
            TableName: IRAutomation-DataStorageStack-MessagesTable05B58A27-16054E0SDUCWI
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY

Outputs:
  StreamSimulationApi:
    Description: "API Gateway endpoint URL for the Stream Simulation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  StreamSimulationFunction:
    Description: "Stream Simulation Lambda Function ARN"
    Value: !GetAtt StreamSimulationFunction.Arn
